@startuml Parrot

start

:Open Log file for reading;

repeat
    :Parse Log Command;
    if (command is ?) then (Yes)
        :skip until next command;
    else (No)
        :Execute Command;
        
        fork
            :pop command from queue;
            :write command;
            :write log to buffer;
            :wait for answer of package fetcher;
            :push command to queue;
        fork again
            :read packages;
        fork again
            :push command to queue of serial_communication;
            :wait for answer;
        end fork

        repeat 
            :Parse Log;
            :Parse log in buffer;
            if (logs are equal) then(No)
                :throw error;
                end
            else (Yes)
            endif
        repeat while (log is command) is (No) not (Yes)
    endif
repeat while (there are unparsed logs left) is (Yes) not (No)

:Close log file;

end

@enduml